viewMorePostLink: /blog/
author: amigos-dev-Vlad
defaultKeywords:
  - amigos-dev
  - hugo
  - go
mainSections:
  - blog
defaultDescription: Made using Hugo
facebook_site: ""
twitter_site: AmigosDev
default_sharing_image: img/sharing-default.png
enableGoogleMaps: true
googleMapsApiKey: ""
latitude: "-12.043333"
longitude: "-77.028333"
style: default
formspree_action: https://formspree.io/sample/of/endpoint
contact_form_ajax: false
enableRecaptchaInContactForm: false
googleRecaptchaKey: site_key_for_google_recaptcha
about_us: <p>We are three amigos, read more in About section.</p>
copyright: Copyright (c) 2022 - 2023, Amigos Development; all rights reserved.
date_format: January 2, 2006
dropdown_mouse_over: false
disabled_logo: false
logo_text: Amigos Development
logo: img/homelogo_wide.png
logo_small: img/logo-small.png
contact_url: /contact
address: "<p class=\"text-uppercase\"><strong>Amigos Development, LLC.</strong>
  \        <br>Washington, WA
  \        <br>
  \        <strong>USA</strong>
  \      </p>
  \      "
permalinks:
  blog: /blog/:year/:month/:day/:filename/
topbar:
  enable: true
  text: "<p class=\"hidden-sm hidden-xs\">Contact us  hello@amigos-dev.com.</p>
    \      <p class=\"hidden-md hidden-lg\"><a href=\"tel:+420 777 555 333\"
    data-animate-hover=\"pulse\"><i class=\"fas fa-phone\"></i></a>
    \      <a href=\"mailto:hello@amigos-dev.com\"
    data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>
    \      </p>
    \      "
widgets:
  categories: true
  tags: true
  search: true
carouselCustomers:
  items: 2
  auto_play: false
  slide_speed: 2000
  pagination_speed: 1000
carouselTestimonials:
  items: 2
  auto_play: false
  slide_speed: 2000
  pagination_speed: 1000
carouselHomepage:
  enable: false
  auto_play: true
  slide_speed: 2000
  pagination_speed: 1000
features:
  enable: true
  cols: 3
see_more:
  enable: false
  icon: far fa-file-alt
  title: Do you want to see more?
  subtitle:
    We have prepared for you more than 40 different HTML pages, including
    5 variations of homepage.
  link_url: "#"
  link_text: Check other homepages
clients:
  enable: false
  title: Our Clients
  subtitle: ""
recent_posts:
  enable: true
  title: From our blog
  subtitle: Blog sub title.
  hide_summary: false
footer:
  recent_posts:
    enable: true
